name: pack

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Make JRE
      run: jlink --module-path $JAVA_HOME/jmods/ --add-modules java.desktop --compress=2 --strip-debug --output tmp_jre
    - name: Upload JRE
      uses: actions/upload-artifact@v2
      with:
        name: jre
        path: tmp_jre
    - name: Make JAR
      run: mvn -B package --file pom.xml
    - name: Upload JAR
      uses: actions/upload-artifact@v2
      with:
        name: jar
        path: target/*-shaded.jar

  zip:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Initialize
      shell: bash
      run: |
        cd unofficial_release
        rm -rf jre jar katago
        mkdir jre jar katago
    - name: Download JRE
      uses: actions/download-artifact@v2
      with:
        name: jre
        path: unofficial_release/jre
    - name: Download JAR
      uses: actions/download-artifact@v2
      with:
        name: jar
        path: unofficial_release/jar
    - name: Make ZIP
      shell: bash
      run: |
        cd unofficial_release
        make kata
        make zip
    - name: Upload ZIP
      uses: actions/upload-artifact@v2
      with:
        name: lizzie_unofficial_release
        path: unofficial_release/tmp_Lizzie-*.zip
